name: Lint and Test

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint flake8

      - name: Run pylint
        run: |
          pylint libml/ tests/ --exit-zero

      - name: Run flake8
        run: |
          flake8 libml/ tests/ \
          --max-line-length=100 \ 
          --ignore=E501,E203,E266,E501,W503,F403,F401 \
          --exclude=.git,__pycache__,build,dist,tests